### ISSUE TITLE
Required fields should default to the empty string

### ISSUE THREAD

**Issue by dpjanes** [sparkfun/phant#101]
Issue:
Currently when a new record is added, every defined field is required. This seems somewhat onerous. 

Proposed solution:
Default missing values to the empty string.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
