### ISSUE TITLE
POST to http://data.sparkfun.com/streams gives nonsense result

### ISSUE THREAD

**Issue by dpjanes** [sparkfun/phant#102]
Issue:
When I POST to http://data.sparkfun.com/streams to create a new stream, a nonsense result is returned. This works with a local Phant server. 

Proposed solution:
I believe SparkFun is disallowing this operation, but the result should be 403 Not Allowed in this case.

Code:

```
var unirest = require('unirest')

unirest
    .post("http://data.sparkfun.com/streams")
    .headers({ 'Accept': 'application/json' })
    .type('json')
    .send({
        title: "DPJ 111",
        description: "DPJ 111",
        fields: "a,b,c"
    })
    .end(function(result) {
        console.log(result)
    })
```

Result being returned:

```
{ success: true,
  message: 'Cannot read property \'length\' of undefined' }
```

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
