### ISSUE TITLE
Timestamp should be renamed '_timestamp'

### ISSUE THREAD

**Issue by dpjanes** [sparkfun/phant#104]
Issue:
Using <code>timestamp</code> as a field conflicts with a name the user may want to use. For example, SmartThings data records use <code>timestamp</code> also to record the time an event occurred.

Proposed:
All Phant added fields should begin with '_' (or whatever). This allows for a clean separation of Phant keys and user keys, plus it allows Phant to cleanly add new things (e.g. _id) in the future without tears.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
