### ISSUE TITLE
Data not posting with successful response message

### ISSUE THREAD

**Issue by piettetech** [sparkfun/phant#111]
I am sending data to the phant server and I receive the '1 success' message but when I check the stream I don't see the data.  It happens rarely - maybe 1 out of 50 posts, but I am concerned why I received a '1 success' message but the data did not post.

**Comment by andygock** [comment]
@toddtreece @piettetech @mtnscott 

Hi,

Do you any of you know the cause of the "a\n1 success\n\n0" response from the server? I am getting that response each and every time I see a response. It could also be "a\r\n1 success\r\n\r\n0", I didn't really check byte-by-byte.

I'm creating the POST payload with this library, submitting via `client.print(phant.post())` and my "client" library is from <https://github.com/esp8266/Arduino>

Thanks
