### ISSUE TITLE
fields names should be case insensitive on stream post 

### ISSUE THREAD

**Issue by piettetech** [sparkfun/phant#117]
This is not a big issue, more of a feature enhancement - Since the Phant stream setup page defaults to all lower case on the field names, the stream parser should also convert all incoming field names to lower case instead of generating an error.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
