### ISSUE TITLE
How do we request a specific amount of data from phant?

### ISSUE THREAD

**Issue by liudr** [sparkfun/phant#126]
Phant is great for uploading. It's simple and elegant. On the other hand, how about make a simple elegant data retrieval method such as retrieve according to a few criteria:
1. extract from record number (oldest being 0 and newest being -1) for a fixed length of records. This way we can extract records for plotting, such as last 1024 data points. page=1 won't do it. It seems to be extracting the most recent data that are not filling up a page yet, so its length is variable and up to 50K but down to say 1 data point. Having the ability to extract last X data points is essential for plotting.
2. extract according to time stamp of upload. Say extract from time stamp xxxxx and 1024 records since that time stamp. This helps logging data offline. Say you want to download your data, you would be worried that you download the whole thing will waste sparkfun bandwidth or time or having a lot of duplicate data. You would be more interested in download say 10/20-10/30 data and save on your computer for further analysis. It doesn't have to be an internet of useless sensors but could be a teaching and/or research tool for regular data upload and extraction so decent records can be kept. Right now it's just for play (sorry for asking for too much).
3. Here is just a thought. When you request metadata of a stream, there should be some custom name=value pairs, that are only kept until it has been requested once, and then erased. It's like a messaging system, where one party posts a message and the other retrieves it, at which time the message disappears. This way I can use one client to set a name=value pair for the data logger to retrieve later. The pair could be "delay_minutes=15" so that when the data logger retrieves it, it alters its data collection period to 15 minutes. Without this, the data logger is just a passive thing and can't be interacted with. I don't think that is most useful in many cases. I use this on some projects to tell loggers deployed in remote areas that it's time to restart or turn on heat to brave the cold :)
Thanks for your time!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
