### ISSUE TITLE
Sorting data?

### ISSUE THREAD

**Issue by liudr** [sparkfun/phant#128]
Is there any way to sort data say in increasing order of a particular column?
Background:
I am working on extracting data within a certain date range for download. I was successful with the gte[index]=xxx and lte[index]=xxx filters. I was able to get data that are within a range of my time stamp (not upload but data collection stamps, could differ if logger temporarily loses internet connection, pretty often if it rains and cloud moves in to block cell signal).

The output was exactly what I asked for, except for order is reversed, with most recent data in the front. I would like to request a sort option so that the output data are sorted according to increasing or decreasing order of a certain column, after the filters have been applied. This would be awesome! Thank you!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
