### ISSUE TITLE
Web Socket updates failing on data.sparkfun.com

### ISSUE THREAD

**Issue by lectroidmarc** [sparkfun/phant#134]
Not sure if this is the right place, but it appears that real time web socket updates are no longer working on data.sparkfun.com.  Or is it "just me"?

I'm seeing "Error: Connection refused: Not authorized" every few seconds in the console.

**Comment by lectroidmarc** [comment]
Thought I'm ping this again.

I have a new project and would like to use Web Socket support on data.sparkfun.com, but it still seems to be turned off.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
