### ISSUE TITLE
Data can be returned out of order

### ISSUE THREAD

**Issue by rvnash** [sparkfun/phant#136]
The documentation states that the data for the 'output' command will be returned in reverse chronological order. Well, here is my URL, and a snippet from the returned result. It isn't in order. What gives?

https://data.sparkfun.com/output/1nZWY1rDoVFEv436oM3l.csv?eq[sensor_board]=garage&eq[sensor_name]=temperature&timezone=America/New_York&limit=500&gt[timestamp]=yesterday

sensor_board,sensor_name,event_type,value,timestamp
garage,temperature,report,35.2400,2015-01-08T22:04:56-05:00
garage,temperature,report,35.4200,2015-01-08T21:36:55-05:00
garage,temperature,report,35.2400,2015-01-08T22:03:56-05:00
garage,temperature,report,35.4200,2015-01-08T21:35:54-05:00
garage,temperature,report,35.4200,2015-01-08T22:00:55-05:00
garage,temperature,report,35.4200,2015-01-08T21:34:55-05:00
garage,temperature,report,35.4200,2015-01-08T21:59:55-05:00
garage,temperature,report,35.4200,2015-01-08T21:58:55-05:00
garage,temperature,report,35.6000,2015-01-08T21:57:55-05:00
garage,temperature,report,35.6000,2015-01-08T21:56:55-05:00
garage,temperature,report,35.2400,2015-01-08T21:32:55-05:00
garage,temperature,report,35.2400,2015-01-08T21:31:55-05:00
garage,temperature,report,35.6000,2015-01-08T21:54:55-05:00
garage,temperature,report,35.6000,2015-01-08T21:53:55-05:00
garage,temperature,report,35.2400,2015-01-08T21:30:54-05:00
garage,temperature,report,35.6000,2015-01-08T21:52:55-05:00
garage,temperature,report,35.2400,2015-01-08T21:29:55-05:00
garage,temperature,report,35.6000,2015-01-08T21:49:55-05:00
garage,temperature,report,35.2400,2015-01-08T21:28:54-05:00
garage,temperature,report,35.6000,2015-01-08T21:48:55-05:00
garage,temperature,report,35.2400,2015-01-08T21:27:54-05:00
garage,temperature,report,35.4200,2015-01-08T21:46:55-05:00
garage,temperature,report,35.2400,2015-01-08T21:26:54-05:00
garage,temperature,report,35.4200,2015-01-08T21:44:55-05:00
garage,temperature,report,35.4200,2015-01-08T21:43:54-05:00
garage,temperature,report,35.0600,2015-01-08T21:24:54-05:00
garage,temperature,report,35.4200,2015-01-08T21:41:54-05:00

**Comment by franko553** [comment]
I am having the same issue.
Is there a fix for this or a way to vote for this issue?

**Comment by rvnash** [comment]
Sorry franko,

It has been some long time since I submitted the issue and I have never
received a satisfactory response. I moved on and rolled my own phant-like
server more suited to my needs. Good luck.

- Rich


- Richard Nash

**Comment by erikhallqvist** [comment]
Sorry about this and not being responsive to Phant issues. We have a new (for Phant, not new to SparkFun) developer digging into Phant and he will have this on his task list. It'll be a while longer before he gets to it, sadly, as he's out on vacation for a few more weeks.  

Please keep submitting issues as you run in to them, as we're about to give Phant some serious love again.

**Comment by blacktigersoftware** [comment]
erikhallqvist - where can I put enhancement requests.  I would've PM'd you, but I can't..... If Phant is going to  get some love, would like to submit a request...

**Comment by erikhallqvist** [comment]
I think in the past, external feature/enhancement requests have been filed as issues, which isn't exactly optimal, but it does keep everything in the same place. I'm not sure I want to make decisions on behalf of the new guy responsible before he's got his workflow going, so if you could hold out another month or so (or if you think you're going to forget, maybe submit an issue), that'd be helpful.  

I'll make sure to talk to the dev and the rest of the team about what we wants to do about feature requests once he gets back to work, though.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
