### ISSUE TITLE
page parameter is applied before filters

### ISSUE THREAD

**Issue by cubeberg** [sparkfun/phant#142]
It would be nice to be able to page filtered results.  Unfortunately if I use a filter and ask for the first page, I only get filtered results from the first page, instead of a full page of filtered results.  
For instance - https://data.sparkfun.com/output/RMGr518yq2iN4WGbA5Zg.json?eq[door]=1&page=1 doesn't return results (at  the current moment) but https://data.sparkfun.com/output/RMGr518yq2iN4WGbA5Zg.json?eq[door]=1&page=2 does.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
