### ISSUE TITLE
having a few server crashes...

### ISSUE THREAD

**Issue by DanwithArduino** [sparkfun/phant#143]
Server is dumping this error: 

![image](https://cloud.githubusercontent.com/assets/10458867/6417636/b6fd242e-be7c-11e4-9bac-0aec6ec94064.png)

and this above it: 
![image](https://cloud.githubusercontent.com/assets/10458867/6417642/c36e57fa-be7c-11e4-9fee-746fb8ea2ad6.png)

server always comes back fine, but its a little problematic. tighter security measures seems to have exacerbated the problem but it was having similar issues before when everything was wide open (then i got a distressed email from digital ocean....)

**Comment by StuartHickey** [comment]
Hi, I'm having something similar with a few errors being thrown when I start my Phant server. Did you get to the bottom of this issue?

**Comment by DanwithArduino** [comment]
unfortunately no. have you found the bug yet?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
