### ISSUE TITLE
phant leaks filedescriptors with ?page=1

### ISSUE THREAD

**Issue by andete** [sparkfun/phant#144]
phant server is leaking file descriptors of the stream.csv when doing ?page=1 requests.
Workaround is to use ?limit=10 e.g. which doesn't seem to have the issue.

lsof -p 29629 | grep stream.csv | wc -l
77
lsof -p 29629 | grep stream.csv | wc -l
82
lsof -p 29629 | grep stream.csv | wc -l

Eventually it reaches 1024 open files and phants exists with EMFILE.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
