### ISSUE TITLE
jsonp support for stream metadata?

### ISSUE THREAD

**Issue by karlp** [sparkfun/phant#145]
Hi, I was trying to load the stream metadata, from http://data.sparkfun.com/streams/<public_key>.json but I can't get it to load without jsonp on my own site.

Requesting datatype jsonp, like for the "data.s.c/output/key.json" urls doesn't work.

**Comment by MikeTeachman** [comment]
+1

**Comment by jywarren** [comment]
+1 - this would be super useful!

**Comment by jywarren** [comment]
I'd attempt changes/PR myself, but wasn't able to find the relevant code; https://github.com/sparkfun/phant/blob/master/lib/http_output.js doesn't seem to list the metadata responses. Perhaps it's not an application-specific response, but generated by one of the dependencies or something? Sorry, not that familiar with the codebase.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
