### ISSUE TITLE
how to backup data?

### ISSUE THREAD

**Issue by mikewen** [sparkfun/phant#147]
I am new to phant, is there a way to back up data ?

**Comment by d1runberg** [comment]
Hi,

Probably the best way to backup your data is to download it on a periodic
basis or write a script to do so automatically. You can download in a
number of formats, json or csv being probably the most useful for backing
up.

**Comment by mikewen** [comment]
Sorry, what I mean if I install phant on my local server. 
How can I backup all the data?
Which directory should I look for?

**Comment by d1runberg** [comment]
Are you running this on a linux machine, did you install globally or to a
specific location...i.e your node packages directory.

Sorry, what I mean if I install phant on my local server.
How can I backup all the data?
Which directory should I look for?

—
Reply to this email directly or view it on GitHub
<https://github.com/sparkfun/phant/issues/147#issuecomment-85218117>.

**Comment by mikewen** [comment]
Yes. I am running Ubuntu, path: /usr/local/lib/node_modules/phant

phant@6.8.0 /usr/local/lib/node_modules/phant
├── wez-telnet@0.1.1
├── dotenv@0.2.8
├── routes@1.2.0
├── xml@0.0.12
├── formidable@1.0.17
├── qs@1.2.2
├── async@0.9.0
├── phant-keychain-hex@0.2.1 (hashids@0.3.3)
├── JSONStream@0.8.4 (through@2.3.6, jsonparse@0.0.5)
├── csv-write-stream@0.1.2 (through2@0.4.2)
├── phant-stream-csv@2.1.1 (log-rotate@0.2.7, csv-string@2.2.5, mkdirp@0.3.5, csv-streamify@1.0.0, rimraf@2.3.2)
├── datejs@1.0.0-rc3
├── phant-meta-nedb@3.1.1 (node-uuid@1.4.3, lodash@2.4.1, nedb@0.10.11)
├── moment-timezone@0.2.5 (moment@2.9.0)
└── phant-manager-http@4.5.10 (serve-favicon@2.2.0, moment@2.9.0, body-parser@1.12.2, express@3.20.2, express-handlebars@1.2.2)

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
