### ISSUE TITLE
UNIDATA Data format: netCDF

### ISSUE THREAD

**Issue by mhoecker** [sparkfun/phant#148]
You should think about including netCDF
http://www.unidata.ucar.edu/software/netcdf/
as an output type. Better yet, e-mail/call up UNIDATA 
http://www.unidata.ucar.edu/
and getting them to contribute code to phant that includes it.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
