### ISSUE TITLE
Can I set access control on my own phant server?

### ISSUE THREAD

**Issue by liudr** [sparkfun/phant#149]
I understand that sparkfun phant server is public so all streams are public. If I install phant on my computer, how do I control access?
Example:
I want user1 to have access to streams 1, 2, 3 etc.

Thanks!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
