### ISSUE TITLE
postings in the server fail for few minutes for regular interval..

### ISSUE THREAD

**Issue by amreenasma** [sparkfun/phant#150]
I have been working on module with application of posting sensor data in your server by creating a stream.It has been in continuous working for few months now. For past few weeks I have noticed a issue that data posting stops for 5 minutes very regularly(data is posted for 3-4 minutes then stops for 5 minutes or so).I have checked my modules and feel they are working fine individually.so plz help me with the issue.

thanx...!!

**Comment by cwray** [comment]
We have had a small problem with the service last week. Problem is fixed now. let us know if you have any more connectivity problems.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
