### ISSUE TITLE
Modified timestamps

### ISSUE THREAD

**Issue by chatelao** [sparkfun/phant#151]
- My weatherstations is sometimes offline and I will store the data locally in an EEPROM

- To upload the collected data, I need to set timestamp myself, based on the real-time clock (RTC)

**Comment by nseidle** [comment]
I've had this problem as well. Checkout my [weather station](https://learn.sparkfun.com/tutorials/weather-station-wirelessly-connected-to-wunderground) tutorial. Best way to fix it is to create an extra column in your channel for your own local time stamp. The time stamp on phant will not be user modifiable; it's core to how phant works.
