### ISSUE TITLE
Timestamp format != timestamp query format

### ISSUE THREAD

**Issue by xsk8rat** [sparkfun/phant#152]
Maybe this is kind of a annoyance or enhancement?
The time stamp format follows the international standards "Year-Month-Day" and the query (kind of) follows the US format of "Month/Day/Year" but with the slashes replaced by dashes. It's sort of a jumble. 

Since everything is already implemented like this, it may mess everyone up to change it. So I can understand if this is rejected. Thank you!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
