### ISSUE TITLE
Adding mqtt to phant

### ISSUE THREAD

**Issue by olskyy** [sparkfun/phant#154]
Hi there,

I have installed phant locally, and trying to add mqtt support, is there any guide on how to configure phant-server-mqtt and input/output?

thank you!

**Comment by q2dg** [comment]
Still waiting...come on, guys...

**Comment by sanderboele** [comment]
I want to know!

**Comment by erniberni** [comment]
Same question for me

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
