### ISSUE TITLE
Install steps for Ubuntu Server -- any version

### ISSUE THREAD

**Issue by blacktigersoftware** [sparkfun/phant#157]
Had a bit of a time trying to get phant installed on a Ubuntu Server 14.04.02.  Appears node.js install package from apt-get is behind, got warning when doing npm install.  Eventually, nothing worked.  Rebuilding node.js from source, hope that fixes it.  Would love to use the Vagant method, but I'm running Ubuntu Server as a VM on server host machine and can't run VirtualBox.

**Comment by blacktigersoftware** [comment]
Build just finished.  phant appears to be running fine.  
steps I took.  Not optimal, as I got the wrong version of node.js, but still this is all the steps I took (from memory).  Should be cleaned up and tested for real.... :)

install Ubuntu Server 14.04.02 x64 with only SSL selected
sudo apt-get update
sudo apt-get install nodejs
sudo apt-get install npm
sudo npm install -g phant
cd ~
mkdir tmpbuild
cd tmpbuild
wget https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
gunzip nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
tar -xf nodejs.org/dist/v0.12.7/node-v0.12.7.tar
cd node-v0.12.7
./configure
make
sudo make install
phant &

**Comment by rajshah4** [comment]
Thanks for posting the step by step instructions, they worked pretty well, here is my revised version:
sudo apt-get update
sudo apt-get install nodejs
sudo apt-get install npm
sudo npm install -g phant
cd ~
mkdir tmpbuild
cd tmpbuild
wget https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
gunzip node-v0.12.7.tar.gz
tar -xf node-v0.12.7.tar
cd node-v0.12.7
./configure
make
sudo make install
phant &
(Got an error, did some research and the following)
apt-get install nodejs-legacy
phant &
(it worked!!)

**Comment by chronoglass** [comment]
you can also ln /usr/bin/nodejs /use/bin/node as long as you don't plan on using the node radio software on the same machine

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
