### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by blacktigersoftware** [sparkfun/phant#158]
## Got the following on my phant console:

events.js:85
    throw er; // Unhandled 'error' event

Error: read ECONNRESET
    at exports._errnoException (utils.js:746:11)
##     at TCP.onread (net.js:559:26)

Then the thing crashed.

**Comment by blacktigersoftware** [comment]
line numbers might not match up with what you got.  I had to rebuild node.js for my machine.  The only thing that was happening was that I was posting data from a device at the time.  I believe the real bug is ECONNRESET needs to be handled appropriately and not crash the service.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
