### ISSUE TITLE
Error Stream not found

### ISSUE THREAD

**Issue by chrowe** [sparkfun/phant#159]
https://data.sparkfun.com/streams/VGAXp1b2bgtmVJK9JqMJ
- I got the New Stream Created! email Jul 31, 2015, 12:43 AM
- I set this up and had data uploading to it.
- I was able to see the data from analog.io

Now it seems the stream is gone.

**Comment by mitmas** [comment]
Have had the same thing happpen to me. ??

**Comment by JRDoty3** [comment]
I also cannot find a stream created on 30 July 2015 but can find the stream created on 18 July 2014.

**Comment by mitmas** [comment]
Seems newly created streams are missing but older one are still there.

**Comment by puckettgw** [comment]
We're looking into the issue -- thank you for your report!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
