### ISSUE TITLE
"Stream Alias" field defaulted back to "nist_weather" when editing stream information

### ISSUE THREAD

**Issue by sweber6106** [sparkfun/phant#160]
When editing stream information, the various fields correctly display the data used at creation time.  The one exception to this is the "Stream Alias" field which is defaulted to "nist_weather".

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
