### ISSUE TITLE
Are there plans to add the ability of control remote actuators?

### ISSUE THREAD

**Issue by q2dg** [sparkfun/phant#161]
Sorry if I'm asking off-topic...I think phant.io would be even greater than it already is if it allowed to send POST queries with custom orders to be received by an attached device, as an Arduino. In other words: allow input of data not only from device to cloud but from cloud to device.
Thanks a lot

**Comment by q2dg** [comment]
I've found and example from Adafruit.io (https://learn.adafruit.com/adafruit-io-basics-digital-output/arduino-wifi). It subscribes Arduino (via MQTT's library) to a feed made of the orders sent from the browser to their online service. It just an idea...

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
