### ISSUE TITLE
Send email, pushbullet?

### ISSUE THREAD

**Issue by iLLiac4** [sparkfun/phant#162]
Is it possible to add actions if something happens. Lets say if temp drops under 20 then send email or. push pushbullet?
Or if there is any input then send email - useful in case of smoke detector.

TNX

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
