### ISSUE TITLE
Realtime updates from data.sparkfun.com?

### ISSUE THREAD

**Issue by lectroidmarc** [sparkfun/phant#163]
When data.sparkfun.com launch it supported realtime updates via websocket.  This worked once (#70) then stopped (#134).  I do think this would be a cool feature instead of resulting to polling ;).

**Comment by Sequoia** [comment]
:+1:

**Comment by bmjbmj** [comment]
:+1: 

Any form of configurable triggers like on Cosm/Xively that 'calls' an URL or uses websocket or what ever is needed for alarms and to react to a new value by eg. open closing a shutter.

Thnx to the developers for there work!

**Comment by blanchardmatt** [comment]
:+1: 

This seems pretty critical to me.. Currently seeing lots of "Uncaught Error: Connection refused: Not authorized" in the browser console log on all public streams. MQTT is failing repeatedly.

```
j._handleConnack	@	phant-manager.min.js?rev=1445871468039:11
(anonymous function)	@	phant-manager.min.js?rev=1445871468039:11
c.emit	@	phant-manager.min.js?rev=1445871468039:13
j._write	@	phant-manager.min.js?rev=1445871468039:11
k	@	phant-manager.min.js?rev=1445871468039:12
j	@	phant-manager.min.js?rev=1445871468039:12
f.write	@	phant-manager.min.js?rev=1445871468039:12
c	@	phant-manager.min.js?rev=1445871468039:14
c.emit	@	phant-manager.min.js?rev=1445871468039:13
e	@	phant-manager.min.js?rev=1445871468039:12
l.queue.l.push	@	phant-manager.min.js?rev=1445871468039:12
d.onMessage	@	phant-manager.min.js?rev=1445871468039:12
```

Is there a good workaround for now?

**Comment by Sequoia** [comment]
@blanchardmatt is your issue with websockets? Your issue seems to be related to general unavailability of data.sparkfun (which I have ticketed [here](https://github.com/sparkfun/phant/issues/168)) :)

**Comment by blanchardmatt** [comment]
@Sequoia - I'm definitely noticing general ups and (lots of) downs with availability and response time sitewide, but this issue is specifically and consistently arising in the MqttClient _handleConnack method. 

Open any stream on the site in your browser - https://data.sparkfun.com/streams/LQExmjVDdAfxozE5ZG9p for example. Open the browser Developer Tools network tab and note the unending repeated requests to wss://data.sparkfun.com/mqtt. These are all resulting in "Uncaught Error: Connection refused: Not authorized" in the console.

I wouldn't be surprised if these unrelenting requests and errors are what is bringing the whole data.sparkfun.com site to it's knees..

**Comment by lectroidmarc** [comment]
Yeah, there's websocket functionality in Phant itself which seems to be disabled on data.sparkfun.com, hence the repeated "Uncaught Error: Connection refused: Not authorized" in the console.

Then there's also #168 which seems to be telling of something else, dead server in a cluster maybe?  I do concur that all these websocket connection attempts and connection timeouts can not be good for overall reliability :/.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
