### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING in Chrome on data.sparkfun.com

### ISSUE THREAD

**Issue by lectroidmarc** [sparkfun/phant#164]
It looks like Chrome fails _occasionally_ with an `ERR_INCOMPLETE_CHUNKED_ENCODING` error on data.sparkfun.com.

It appears that Chrome doesn't like chunked XHR requests with no content-length being sent.  This was fixed in Phant (#120) but it doesn't appear it was pushed to data.sparkfun.com (or possibly not to every instance?).

This makes polling a bit problematic (which without websockets (#163, #134, :)) is necessary.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
