### ISSUE TITLE
Unable to create deploy config at https://data.sparkfun.com/config

### ISSUE THREAD

**Issue by followfung** [sparkfun/phant#165]
I'm not sure if this actually belongs here, but I've been trying to download the phant server configurator files, but it won't work for me.

Seems to be some issue with the JavaScript on the page? `Uncaught TypeError: Cannot read property 'http' of undefined`

Has anyone else had this issue?

**Comment by manosv** [comment]
Yes i have the same problem as you

**Comment by Theteendevs** [comment]
Yeah same issue here......

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
