### ISSUE TITLE
Running Phant on Startup

### ISSUE THREAD

**Issue by benandrews54** [sparkfun/phant#166]
Hi,

I am having issues with running Phant automatically on startup.

I have tried adding "@reboot phant &" to crontab as well as "@reboot /usr/local/bin/phant &" but neither worked. I also tried adding both of these to my /etc/rc.local" files but again neither worked.

If I set the Pi to autologin and add "phant &" to "/home/pi/.bashrc" it does work. However, this means that whenever I SSH in and login, the Pi tries to start phant again which throws errors, etc.

Is there any way around this problem?

**Comment by nealzip** [comment]
@benandrews54  
If you add /usr/local/bin/phant & to your rc.local should work. I'm not sure what the @reboot is about.
You may want to run which phant to confirm phant is located in the .usr/local/bin directory. 
Mine was in /usr/bin/phant/

Neal
Darn Spell Check keeps changing phant to plant!

**Comment by benandrews54** [comment]
Hi Neal,

The @reboot is for crontab. I believe it specifies that the command should be run on startup. I wasn't very clear but when I originally placed the commands into rc.local it was without the @reboot.

I have confirmed that phant is in /usr/local/bin and rc.local is pointing to the correct path.

Here is my rc.local file:

```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

/usr/local/bin/phant &

modprobe i2c-dev
# Calibrate the clock (default: 0x47). See datasheet for MCP7940N
i2cset -y 1 0x6f 0x08 0x47
modprobe i2c:mcp7941x
echo mcp7941x 0x6f > /sys/class/i2c-dev/i2c-1/device/new_device
hwclock -s
```

**Comment by nealzip** [comment]
Your rc.local file looks the same as mine. I am using it on AWS (Amazon) and it works. 

Does phant work if you just type sudo /usr/local/bin/phant & ?
Do you see website on port 8080?

Regards,
Neal

**Comment by reusewaterak** [comment]
I had similar issues and had to include the startup command with nohup and a null log file.  Here is my command.  

nohup phant >/dev/null 2>&1 &

**Comment by Vulpecula-nl** [comment]
You have to install the `forever` module in `npm`. For howto see bottom part of this page: http://phant.io/beaglebone/install/2014/07/03/beaglebone-black-install/

This is written for the Beaglebone but I have tested on my Ubuntu 16.04 server and it works! For me it also solved an out-of-memory issue!

**Comment by adamfowleruk** [comment]
The above comments work if you don't mind running from boot as the root user. If, however, you've logged in as the 'pi' user and used phant, then you've already configured your streams as that user. Thus starting it from rc.local or init scripts means you 'lose' your stream configurations. Ideally we could do with an OOTB fix for this from the phant team themselves, to point out best practice without losing configuration.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
