### ISSUE TITLE
Creating stream using the API

### ISSUE THREAD

**Issue by jsandv** [sparkfun/phant#169]
Is it not possible to create a new stream using the Phant-API?
If it is possible how does the http post format look like?

**Comment by jsandv** [comment]
Nobody answering these posts? Its an easy question.....

**Comment by ozroc** [comment]
I have the same question.
Is this feature already planned?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
