### ISSUE TITLE
Deleting rows of data

### ISSUE THREAD

**Issue by jsandv** [sparkfun/phant#170]
Is it possible to delete rows of data from a stream?!
The clear command removes all......

**Comment by m4ddav3** [comment]
You would need to find your target rows from the csv files directly. Take a backup first, as phant isn't very good at dealing with unexpected data/formatting/other

**Comment by fuchini** [comment]
Hi, could you expand please. Is it possible to change individual values?

**Comment by m4ddav3** [comment]
Yes, you can change any/all of the data -- it is just stored as CSV text in your phant_streams directory.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
