### ISSUE TITLE
Configure and Deploy is Broken

### ISSUE THREAD

**Issue by bobthewinger** [sparkfun/phant#171]
504 Gateway Time-out

The server didn't respond in time.

When I don't get this error the page comes up, but does not allow any choices to be made.  You get an endless spinner.

**Comment by zahilman** [comment]
I am getting this error too along with 

502 Bad Gateway

I would really like to configure my phant before I deploy any help is appreciated!

**Comment by bcupps** [comment]
Any update on resolving the 502 error? Thanks!

**Comment by jonaslorander** [comment]
I'm getting the 502 and 504 errors as well. Have have been getting them for well over a week now. Any change you might fix this, or Point me in the direction of how to set up phant using MQTT without the configurator?

Thanks!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
