### ISSUE TITLE
timestamp incorrect

### ISSUE THREAD

**Issue by bakerbrown** [sparkfun/phant#173]
Attached is some series data that has been recently collected, if you look at the data the 5th line has a timestamp of 11:23 and the 4th line is 11:12? I would have expected 12:23?

-69,20.67,69.22,2015-12-01T00:15:11.854Z
-72,20.68,69.21,2015-12-01T00:14:41.208Z
-72,20.68,69.27,2015-12-01T00:13:22.406Z
-71,20.7,69.19,2015-12-01T00:11:12.790Z
-71,20.66,69.2,2015-12-01T00:11:23.927Z
-70,20.72,69.28,2015-12-01T00:10:22.886Z
-70,20.68,69.23,2015-12-01T00:09:23.621Z
-71,20.69,69.23,2015-12-01T00:08:23.265Z

**Comment by datacute** [comment]
SparkFun fixed this a few days ago: https://github.com/sparkfun/phant/issues/172

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
