### ISSUE TITLE
CSV to Excel extra spaces

### ISSUE THREAD

**Issue by AlanBC7** [sparkfun/phant#174]
When the .csv file is imported into Excel extra spaces are present between the integer part and the fractional part.  Example 74.123 comes into Excel as 74  .123  This makes Excel think the number is a string "74  .123"

**Comment by datacute** [comment]
I had a very similar problem, which I tracked down to a bug in the ESP8266 Arduino tools I was using to send the float data to SparkFun. Updating the tools fixed the problem for me. SparkFun had been accurately recording the values I was sending with spaces in them.

**Comment by AlanBC7** [comment]
Hi Stephen,

This helps a lot, thank you.  The printout on data.sparkfun.com looks 
good.
The data can be exported to analog.io and plots fine.

Please be a little more specific about what you mean by "update the 
tools"
I am running Arduino 1.6.4 and checked today that 1.6.6 is available.
Or, are you talking about files I downloaded with the Library Manager?
Or, other tools?
I am using the Sparkfun ESP8266 Thing Dev Board.

Thanks for the help.

All the best, Alan

**Comment by datacute** [comment]
I'm using Arduino IDE v1.6.5, and what fixed the problem for me was within Tools | Boards | Board Manager, updating the esp8266.

I saw that I was sending bad data by adding
Serial.println(phant.queryString());
before calling post() or url().

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
