### ISSUE TITLE
Windows Setup Error

### ISSUE THREAD

**Issue by SalvorinFex** [sparkfun/phant#175]
I just tried to get this setup using the vagrant option, things seemed to go well until the very end where I got this message:
![phant_error](https://cloud.githubusercontent.com/assets/2433369/11766121/ed58449e-a12b-11e5-9b56-9c56c9e003ce.png)

There does seem to be somethings missing from these instructions, though.
As I basic user of Git, I knew to run the step #4 & #5 commands in a Git Bash window, but that isn't actually listed there, this would easily throw a novice.

Also of note, this page: https://data.sparkfun.com/config as of midnight PST on Dec. 13th, is throwing a 500 error.

EDIT: Also, when I tried to go to localhost:8080 nothing responded and it timed out.

Please advise.

**Comment by SalvorinFex** [comment]
Four days later and no response, not what I expected!

Also, the web page https://data.sparkfun.com/config is still erroring out:

504 Gateway Time-out

The server didn't respond in time.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
