### ISSUE TITLE
Server returns response with no content at all, but logs an entry anyway

### ISSUE THREAD

**Issue by jasiek** [sparkfun/phant#176]
Have a look at this stream: https://data.sparkfun.com/streams/mKL1nZ6NDpUA148l3V4G

If you scroll back far enough you'll find a sequence of records where the number of records is increasing. My code sends a record to the server and logs an error if it can't find the `1 success` string. Turns out, it seems, that the server accepts these entries but returns an empty response body (without headers). Perhaps one of the backend services is timing out and the load balancer/whatever just returns an empty body?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
