### ISSUE TITLE
wget or curl hangs at full data download

### ISSUE THREAD

**Issue by ghost** [sparkfun/phant#177]
When exporting data (shown here as Sparkfun's Wimp Weather Station Stream) using 'wget -o "https://data.sparkfun.com/output/dZ4EVmE8yGCRGx5XRX1W.csv?gte[timestamp]=12-15-2015&lt[timestamp]=12-16-2015"' or same address and query using "curl" similar issue occurs.  File is downloaded to full extent and then hangs. Using wget the download will restart and try again and suceed.  The issue really is performing queries in the address is resulting in 30 sec download times when the file is fully downloaded at 2 sec and waiting for wget or curl to complete.  This also happens when simply pasting the address in the browser as once data is completely downloaded the indicator that the browser is working remains active for about 30 sec. Please advise.

**Comment by addotson** [comment]
for reference is my log associated with curl


 % Total| Total Data|   % Recieved |Received Data| % Xferd| Xferd Data|  Average Speed Dload| Average Speed Upload|   Time Total  |   Time Spent  |   Time Left | Speed 
---|---|---|---|---|---|---|---|---|---|---|---
  |0   |  0 |   0 |    0 |   0 |    0 |     0 |     0| --:--:--| --:--:--| --:--:--|     0
  |0  |   0  |  0 |    0  |  0  |   0 |     0  |    0 |--:--:--| --:--:--| --:--:--    | 0
  |0   |  0  |  0    | 0   | 0    | 0    |  0     | 0 |--:--:--  |0:00:01 |--:--:--|     0
|100 |12811    |0 |12811   | 0  |   0|   5439   |   0| --:--:--|  0:00:02| --:--:-- | 5437
|100  |136k |   0  |136k    |0     |0  |34646      |0 |--:--:--  |0:00:04| --:--:-- |34657
|100  |136k  |  0  |136k    |0     |0  |27767      |0 |--:--:--|  0:00:05| --:--:-- |27769
|100  |136k   | 0  |136k    |0     |0  |23168      |0 |--:--:-- | 0:00:06| --:--:-- |24506
|100  |136k    |0  |136k    |0     |0  |19875      |0 |--:--:--  |0:00:07 |--:--:-- |25334
|100  |136k    |0  |136k    |0     |0  |17402      |0| --:--:--  |0:00:08| --:--:-- |22348
|100  |136k    |0  |136k    |0     |0  |15476      |0| --:--:--  |0:00:09 |--:--:--  |   0
|100  |136k    |0  |136k    |0     |0  |13934      |0| --:--:--  |0:00:10 |--:--:--   |  0
|100  |136k    |0  |136k    |0     |0  |12672      |0| --:--:--  |0:00:11| --:--:--    | 0
|100  |136k    |0  |136k    |0     |0  |11619      |0| --:--:--  |0:00:12 |--:--:--     |0
|100  |136k    |0  |136k    |0     |0  |10728      |0| --:--:--  |0:00:13| --:--:--     |0
|100  |136k    |0  |136k    |0     |0   |9964      |0 |--:--:--  |0:00:14| --:--:--     |0
|100  |136k    |0  |136k    |0     |0   |9301      |0 |--:--:--  |0:00:15 |--:--:--|     0
|100 | 136k    |0  |136k    |0     |0  | 8721      |0 |--:--:--  |0:00:16 |--:--:-- |    0


curl: (18) transfer closed with outstanding read data remaining

**Comment by ADeeds** [comment]
`wget -O - /dev/null "http://<server>/phant/output/<key>.json?gt[timestamp]=now%20-7%20days&timezone=America/Los%20Angeles" | tr -dc "{" | wc -c` 
That command takes ~6 seconds for me to execute, and wc -c finds 646 JSON objects

`wget -O - /dev/null "http://<server>/phant/output/<key>.json?limit=646" | tr -dc "{" | wc -c`

That command takes 0.5 seconds and returns the same 646 JSON objects. If you watch the output as you download it (in browser or command line), it looks like all of the objects get downloaded, then it takes a really long time for the end of the list (the right square brace) to get sent. I haven't dug into the code,  but I suspect that filtering by timestamp isn't optimized at all (if you're using ?gt[timestamp], it should stop looking and finish sending data once it sees the first timestamp that is too old)

**Comment by ADeeds** [comment]
I submitted #207 , which makes filtering by timestamp significantly faster when you have lots of data and aren't planning on getting all of it

With the PR, the following command takes 0.7 seconds instead of 6.
`wget -O - /dev/null "http://<server>/phant/output/<key>.json?gt[timestamp]=now%20-7%20days&timezone=America/Los%20Angeles" | tr -dc "{" | wc -c`

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
