### ISSUE TITLE
https://data.sparkfun.com/config 

### ISSUE THREAD

**Issue by ghost** [sparkfun/phant#178]
returns 502 Bad Gateway

**Comment by maxmclau** [comment]
Same problem here

**Comment by matrixfox** [comment]
Wow, this issues old in technology years... I get this error when using a web browser and parsing data to sparkfun...

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
