### ISSUE TITLE
Is Sparkfun data down, or malfunctioning?   

### ISSUE THREAD

**Issue by rfarmer0103** [sparkfun/phant#179]
What's happened to Sparkfun data?  I've been logging data every five minutes to:  
http://data.sparkfun.com/streams/EJAVpX3X2gCbW7oLoKam

but error 35 from sparkfun has been returned for every data post since last night.  Is Sparkfun data down ?  or malfunctioning?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
