### ISSUE TITLE
302 to https when using ethernet shield on arduino

### ISSUE THREAD

**Issue by scotty-7** [sparkfun/phant#180]
I tried using an arduino and an ethernet shield to grab data from the csv page of my data stream. I keep getting a 302 redirect to the https page, which the arduino clearly can't handle. Any way around this?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
