### ISSUE TITLE
http post built with phant library returns 0 characters

### ISSUE THREAD

**Issue by mparsche** [sparkfun/phant#181]
When I use the phant library on my Arduino, I create a http POST request as follows:
POST /input/VGLpo4MVwntRwRQL0g88.txt HTTP/1.1
Host: data.sparkfun.com
Phant-Private-Key: 9YK2GePME8tgWgRxVbmm
Connection: close
Content-Type: application/x-www-form-urlencoded
Content-Length: 138

alarmreadylight=0&alarmarmedlight=0&alarmbypasslight=0&alarmzone1light=1&alarmzone2light=0&alarmzone3light=0&alarmzone4light=0&alarmbeep=0

When I perform a Client.println() on my WiFi Shield I get 0 characters returned

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
