### ISSUE TITLE
Custom configuration utility (Deploy link) fails

### ISSUE THREAD

**Issue by chopsuei3** [sparkfun/phant#182]
When clicking the Deploy link from https://data.sparkfun.com/, I get a 502 or 504 error after waiting for about 30 seconds.

Confirmed on both Firefox and Chrome.

Will this be fixed?

**Comment by jonaslorander** [comment]
It doesn't seem to work if you run phant-manager-sparkfun (which is what's running on data.sparkfun.com) on your own server either :(
It would be really nice if this were fixed!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
