### ISSUE TITLE
Disable Delete Key?

### ISSUE THREAD

**Issue by fohnbit** [sparkfun/phant#184]
Hello,

my phant are running on my Linux System.
is it possible to disable the Delete Key function? I want to delete anytime the streams.
Also modify over the webGui would be great, if this is in my case always possible.

Would be great, if the webGui has user/password.

Thank you!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
