### ISSUE TITLE
Emailing a Copy of the Public and Private Keys Not Working?

### ISSUE THREAD

**Issue by bboyho** [sparkfun/phant#185]
After creating a new data.sparkfun.com stream, there is a button to email a copy of the public and private keys. I had an issue but I thought it was a localized issue. Looks like another customer was having the same issue getting a copy of the keys after hitting the button too.

Can someone look into this please?

**Comment by astroeng** [comment]
I will second this... Just created a new stream and the email did not come through. I created a stream back in July and the email worked fine for that one.

**Comment by Erik-k** [comment]
I created a stream recently (September 2016) and the email feature did not work. I included two emails, a personal @gmail.com one and a corporate one and neither received the email.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
