### ISSUE TITLE
change Timestamp column position in CSV

### ISSUE THREAD

**Issue by gibsop1** [sparkfun/phant#186]
I am using http://dygraphs.com/ to build graphs from data feeds, however it requires the timestamp to be the first column.  Currently I'm using a script to reorder the columns, but it would be nice if you could pass a query string argument to the /output URI to control the Timestamp column location.  This also breaks most graphing tools defaults such as Excel etc.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
