### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by ryanlloydmiller** [sparkfun/phant#187]
Have other people been getting this error a lot lately? Over the last several days I've been getting it on about 5% of posts (~every 10 minutes). Sometimes it takes 10 or 15 attempts over several minutes to get it to go. This is from both of two different devices 1000 miles apart.

I had a similar problem a couple months ago when many people seemed to also be having issues. At that time, changing the https to http seemed to fix the problem. I've tried both forms now and it doesn't seem to matter.

**Comment by astroeng** [comment]
I have seen this a couple of times over the last few days as well. I have seen 504 as well, but I think that might be on my end. However, I have never seen it take my logging app 10 tries.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
