### ISSUE TITLE
Is development still active on this from Sparkfun?

### ISSUE THREAD

**Issue by astroeng** [sparkfun/phant#188]

**Comment by ToniCorinne** [comment]
Our IT team is slowly working on cleaning up features on phant on our backend. They will be looking at more issues/feature requests on GitHub soon!

**Comment by q2dg** [comment]
Last commit is from Nov 2015....

**Comment by zinefer** [comment]
Yes! We are working on a large overhaul.

**Comment by astroeng** [comment]
Any details?

**Comment by Erik-k** [comment]
I'm curious too since the documentation says the next features will include using TCP to directly upload, rather than having to do the kludge of sending HTTP GET requests.

**Comment by Pablo2048** [comment]
Any news?

**Comment by edmaher** [comment]
@zinefer I feel it would be much better for the users if there were more small incremental updates, regular releases, or if there is a major piece of work, it would be great if there was a visible branch. Accepting pull requests would be a great way to get more stuff done.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
