### ISSUE TITLE
using phant-output-mqtt ?

### ISSUE THREAD

**Issue by chrigui** [sparkfun/phant#189]
hi all i just installed phant on the pi and then installed phant-output-mqtt but i cannot see it anywhere... am i missing something ?

thanks.

**Comment by erniberni** [comment]
same for me

**Comment by chrigui** [comment]
Bump

**Comment by erniberni** [comment]
@chrigui: any progress on this ?

**Comment by chrigui** [comment]
@erniberni Nothing yet, i have phant installed on a pi but i don't know how i can use the output there is no documentation for it.
i found this: https://github.com/sparkfun/phant/pull/85
anyone knows any things please share it!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
