### ISSUE TITLE
datastore.js:61  error

### ISSUE THREAD

**Issue by mikegreenpower** [sparkfun/phant#193]
Hi,

**i have this error when i start phant from prompt:** 

\src\node_modules\nedb\lib\datastore.js:61
    if (err) { throw err; }
               ^
Error: toString failed
    at Buffer.toString (buffer.js:528:11)
    at tryToString (fs.js:445:15)
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:436:12)

*_How i can resolve this problem ? *_

Thanks

**Comment by astroeng** [comment]
The line of code you are referencing is from the nedb Node.js module. If you can I would suggest updating that module. something along the lines of "npm update" would be a good start

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
