### ISSUE TITLE
Customise the design of phant?

### ISSUE THREAD

**Issue by lautiamkok** [sparkfun/phant#194]
I just have Phant installed on my local machine. But I wonder if we can customise the design and layout of Phant? If so, any documentations or guides out there for us to follow? I can't the location of HTML files where Phant is installed - /usr/local/lib/node_modules/phant/

**Comment by Erik-k** [comment]
Do you mean customize the appearance of the stream's data (where do you find that by the way?) or the telnet interface?

**Comment by d1runberg** [comment]
@lautiamkok The front end pages are built in handlebars and are present in the http manager. Once you install Phant (assuming globally) go to the directory you specified and navigate to the `phant-manager-http` module directory in your `node-modules` directory. Look for `views`. Go ahead and change away!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
