### ISSUE TITLE
how can I change the postgres database setting

### ISSUE THREAD

**Issue by jianwel** [sparkfun/phant#195]
I am thinking to link phant with our postgres-xl database. Any suggestion on how to change the phant code/configuration to do that?

**Comment by m4ddav3** [comment]
You would need to create a package specifically for this, and register it as an Output.
Take a look at [phant-stream-csv](https://github.com/sparkfun/phant-stream-csv) for an ideal as to what is needed.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
