### ISSUE TITLE
Phant is throwing a RangeError

### ISSUE THREAD

**Issue by dklinkman** [sparkfun/phant#198]
This is a local phant instance.  It was up and running for awhile but now getting the following on startup:
# phant

(node:20144) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
phant http server running on port 8080
phant telnet server running on port 8081
/usr/local/lib/node_modules/phant/node_modules/phant-meta-nedb/node_modules/nedb/lib/datastore.js:61
    if (err) { throw err; }
               ^

RangeError: File size is greater than possible Buffer: 0x3fffffff bytes
    at FSReqWrap.readFileAfterStat [as oncomplete](fs.js:386:11)
# 

I don't think the warning is the problem.  I'm pretty sure it's the error towards the end. I did update Nodejs and phant but this error was occurring on the older version also.

I don't know if it's the culprit but my streams.db file under phant_streams is 3.5GB in size.  All the other files are smaller but some do range up to a little less than 512MB in size.

streams.db just seems to repeat the same data over and over except for a few fields.  Is it safe to edit that or is it possible to do?

Thanks

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
