### ISSUE TITLE
Units in documentation of limits are ambiguous

### ISSUE THREAD

**Issue by jacobsa** [sparkfun/phant#199]
[data.sparkfun.com](https://data.sparkfun.com/) says this:

> Each stream has a maximum of 50mb.

Please clarify whether "mb" means megabit (10^6 bits), megabyte (10^6 bytes), mebibit (2^20 bits), mebibyte (2^20 bytes), or millibit (10^-6 bits).

Consider using "MB" or "MiB" to make this clearer. :-)

**Comment by jschulenklopper** [comment]
While this is a valid request for clarification on the documentation of the _service_ provided at data.sparkfun.com, it is not an issue related to the _code of phant_ powering the service.
The code does not specify that limit, the limit isn't mentioned in the documentation of the code AFAICT, and the home page of data.sparkfun.com isn't hosted in this repository at GitHub.
Most likely an email to data@sparkfun.com should provide a resolution on this issue.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
