### ISSUE TITLE
Is it possible to post data to a single field instead of all?

### ISSUE THREAD

**Issue by ilovebeer** [sparkfun/phant#201]
When I try to post data to a single field (e.g. ch_1) in a stream that has multiple fields defined (e.g. ch_1, ch_2, ch_3, ch_4) 

I get an error:  expecting: ch_2, ch_3, ch_4

Is it possible to post to a single field in a stream that has multiple fields defined? Am I missing something?

It works perfectly if send all 4 fields, however my system is event driven and only sends if there is a change. Sending all fields every time any field changes is not an attractive option.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
