### ISSUE TITLE
Can I enable TLS 1.1?

### ISSUE THREAD

**Issue by MNGregO** [sparkfun/phant#204]
I was trying the tutorial [here](https://learn.sparkfun.com/tutorials/pushing-data-to-datasparkfuncom) and ran into a problem. I was trying to push data to the Sparkfun phant server from my phone which is running Android 4.3. From what I have read, Android 4.3 is only capable of TLS 1.1, and from a test I ran [here](https://www.ssllabs.com/ssltest/analyze.html?d=data.sparkfun.com&hideResults=on), it appears that the Sparkfun server requires TLS 1.2.
The error I got in Android was the following:
`https error: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5f342930: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x5ad6fb86:0x00000000)`
Does anyone have any ideas for me? I'm new to Phant and writing Android code.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
