### ISSUE TITLE
Data Loss

### ISSUE THREAD

**Issue by astroeng** [sparkfun/phant#206]
Did something happen to the server today that reset all data streams?

**Comment by tsayles** [comment]
Looks like all my streams also were reset.

**Comment by gmagiafas** [comment]
Same here. The weird thing is that is shows data usage 100% but only today's data are present!

**Comment by vadysoares** [comment]
My streams were reset too :(
Yesterday data.sparkfun.com was offline for a long time ...

**Comment by edusteinhorst** [comment]
Same here... 100% usage and no data. I hope they can get it back online, I had a lot of important data there

**Comment by structure7** [comment]
Same. Although I think it's showing me 100% _remaining_.  "100% (50.00 of 50 MB) remaining"

**Comment by vadysoares** [comment]
The sever is offline again :( 
We should backup our data ...

**Comment by structure7** [comment]
A little shakey, but I think it's coming back (as of 2016-11-04 01:42Z).

**Comment by edusteinhorst** [comment]
I think it is! I saw my data for a moment. All is not lost :)

**Comment by structure7** [comment]
Just wanted to share what I heard back from Sparkfun tech support:

> Unfortunately we don’t really have a concrete timeline for it. It should be marginally functional now, but our sysadmin is still has to go through and spin up a bunch more mongo database servers for storage and I think that should get everything up and running again (crosses fingers). They usually do things like that over the weekend or at night to minimize impact on how it effects our network, and I know that [the sysadmin] expressed interest in getting it back up and running ASAP – I would guess he has it done by Monday, but that’s just my personal guess.

**Comment by emmmitt** [comment]
We had some issues with our data aging system and our disks filled, this caused the system to become unreachable. 
We changed the database to be on elastic block storage and spun everything back up, we then needed to migrate some data over. 

Thanks for dropping us a note and for using phant. We are keeping an eye on it right now - hopefully we are stable again for a while.

**Comment by tsayles** [comment]
@emmmitt Thanks for the update / back story.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
