### ISSUE TITLE
Data.sparkfun is down?

### ISSUE THREAD

**Issue by spookysys** [sparkfun/phant#208]
I can't seem to push or access data since last night

**Comment by idcrook** [comment]
appears to be back up 2016-11-20T19:38:40Z

**Comment by astroeng** [comment]
I have been getting a ton of 503 Service Unavailable messages recently. Inspired me to add a message buffer to my project.

**Comment by idcrook** [comment]
Guess it's provided a lot of inspiration. The downtime, etc. inspired me to dockerify phant too, so I can host a locally grown database quickly/painlessly. 😄  if interested: https://github.com/idcrook/phant 

A message buffer would be a generally useful client library addon for a IoT logging framework, I would opine. One caveat as I understand it is the phant-assigned timestamps at the server. Can/Does your message buffer account for that limitation? The reason I ask is that part of my requirements involve having the original time series represented alongside my data...

**Comment by astroeng** [comment]
I added a field to my stream that represents the date that the message was created. Uses the same format as the phant timestamp. There might be a better way but I found this to be pretty simple and work.

`char* timeDateString(char* buffer, int buffer_len)
{
  char milliSecondsBuffer[4];
  timespec rawTime;
  struct tm * timeinfo;

  clock_gettime(CLOCK_REALTIME, &rawTime);
  
  timeinfo = localtime(&rawTime.tv_sec);

  strftime(buffer, buffer_len, "%FT%T.xxxZ",timeinfo);

  sprintf(milliSecondsBuffer,"%03ld",rawTime.tv_nsec / 1000000);

  memcpy(strstr(buffer, "xxx"),milliSecondsBuffer,3);

  return buffer;
}`

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
