### ISSUE TITLE
Occasional missing data with response of 200 OK

### ISSUE THREAD

**Issue by astroeng** [sparkfun/phant#209]
I have noticed since adding some retry and buffer logic to my project that once in a while data.sparkfun.com responds that the data was received. However, the data is nowhere to be found in my data stream. I have removed my private and public keys from the message. But from the message I can see that my project generated the message on 2016-11-26T16:01:20.399Z and data.sparkfun.com responded on Sat, 26 Nov 2016 16:01:26 GMT. Which is about 6 second after the message was generated. My project reported that it took data.sparkfun.com 6.558 seconds to send the response.

https://data.sparkfun.com/easy_weather2

WUPLOAD(us, queue):809,1
SEND THREAD:
GET /input/<publickey>?private_key=<privatekey>&mc=691&i_ms=120000&h_ap=109.105&p_in=29.868&t_df=47.0206&l_ir=0&l_uv=0&l_wh=0&wd_d=135.962&ws_mph=1.42436&ws_std=0.489091&ws_max=2.91&ws_dmx=112.5&rf_in=0.11&date=2016-11-26T16:01:20.399Z HTTP/1.1
Host: data.sparkfun.com
User-Agent: raspi-weather
Connection: close

50 39 1 378 127641

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,POST,DELETE
Access-Control-Allow-Headers: X-Requested-With, Phant-Private-Key
Content-Type: text/plain
X-Rate-Limit-Limit: 300
X-Rate-Limit-Remaining: 297
X-Rate-Limit-Reset: 1480176740.681
Date: Sat, 26 Nov 2016 16:01:26 GMT
Connection: close
Transfer-Encoding: chunked
Set-Cookie: SERVERID=; Expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/
Cache-control: private

a
1 success

0

PHANT STATUS: 120000 6558 0 0

**Comment by iamchriskelley** [comment]
Are there any updates on this issue? I'm having the same problem, using an ESP8266 to post to Phant. Something like one in 30-50 posts is returning a 200 OK message but the data aren't showing up in the Phant stream. Kind of a big problem for a datalogging service.

**Comment by astroeng** [comment]
I too still see the issue from time to time. I stood up a google sheets API that allows my weather station to log data in a spreadsheet concurrently with the Sparkfun service. So far no missing data entries with google sheets, but Sparkfun occasionally misses one here and there.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
