### ISSUE TITLE
Error: EMFILE, too many open files

### ISSUE THREAD

**Issue by aham123** [sparkfun/phant#210]
I have installed phant on Ubuntu 16.04.
im using node v7.2.0
Phant has been tweeked from a fork on here to function with node v7.
Node / Phant appears to leak open file descriptors. I have noticed my file descriptors going up as I request a JSONP from a stream to plot a graph using google charts. The same code used on the guide on phant.io

If i keep reloading continuously using an auto refresh in the HTML head tag the file descriptors go up and up until eventually phant prints EMFILE, too many open files to the console and stops working.

I have not seen the file descriptor limit ever reduce in value. Well, I have when im not retrieving data from phant, it may increase by one but then decrease by one a short time later.

I have increased my file descriptor limits to 40000 so phant doesnt crash as often, and i can add a cron job to kill / reload phant every so often.

I use the following command to view the file descriptor limits.

ls /proc/$PID/fd/ | wc -l (finding the pid of node using top)

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
