### ISSUE TITLE
CSV export does not include empty fields, which breaks the header

### ISSUE THREAD

**Issue by lumbric** [sparkfun/phant#212]
The first field comment is empty, which seems to break CSV output:

```
comment,humidity,requester,supply_voltage,temperature,time,timestamp,wifi_signal
19,livingroom,0,21,1484255371,2017-01-12T21:10:21.753Z,-56
19,livingroom,0,21,1484254771,2017-01-12T21:00:19.086Z,-54
19,livingroom,0,21,1484254171,2017-01-12T20:50:16.503Z,-54
19,livingroom,0,22,1484253570,2017-01-12T20:40:13.766Z,-53
```

HTML displays:

```
comment 	humidity 	requester 	supply_voltage 	temperature 	time 	timestamp 	wifi_signal
        	18 	livingroom 	0 	21 	1484195199 	2017-01-12T04:25:43.426Z 	-54
        	18 	livingroom 	0 	21 	1484194594 	2017-01-12T04:15:40.834Z 	-53
        	18 	livingroom 	0 	21 	1484193989 	2017-01-12T04:05:38.249Z 	-53
        	18 	livingroom 	0 	21 	1484193384 	2017-01-12T03:55:35.709Z 	-54
```

Note that comment is empty for all records.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
