### ISSUE TITLE
Data is not ordered by timestamp

### ISSUE THREAD

**Issue by JacquesBB** [sparkfun/phant#214]
in several occasions, the data is not ordered by timestamp. 

Is this normal ?

**Comment by astroeng** [comment]
I have seen the same thing. It gets worse the closer together the reports to the data service are. The closest my reports get is 30 seconds and recently the out of order issue has been getting worse. I previously had selected 30 seconds as it seemed to work most of the time. The nominal report interval for my stream is 120 seconds, which seems to always be in chronological order. 

If I may speculate a bit I think the out of order issue has to do with what I suspect is multiple servers dealing with all of the devices sending in reports. I would bet that the synchronization between the servers is somewhat loose.

**Comment by edmaher** [comment]
I have noticed this too, however, I think the issue is the timestamp generation, not the ordering.
I am pushing data that includes an integer timestamp from the device, so i can see that the data is returned in correct order ( newest to oldest ..... btw I would prefer to be able to reverse this )

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
