### ISSUE TITLE
data.sparkfun.com unable to delete a stream from the manage form

### ISSUE THREAD

**Issue by Suisse00** [sparkfun/phant#215]
I tried to delete my stream using the HTTP UI manage form without success.
Nothing happen (and I really mean nothing)), when clicking the delete button I don't see any error in console nor traffic going to the server.

I tried the latest version (on my own server) without any issue.

I successfully deleted my stream using the HTTP REQUEST ( ttp://data.sparkfun.com/streams/PUBLIC_KEY/delete/DELETE_KEY , well... i did have an 502 error first then a an error about an unfound stream but it worked)

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
