### ISSUE TITLE
How to gracefully stop Phant?

### ISSUE THREAD

**Issue by structure7** [sparkfun/phant#217]
It seems that any time I stop Phant (ctrl-c), then restart, I get an error. This error is usually something to do with `datastore.js:61  if (err) { throw err; }`. I'm guessing this is because, despite my best effort at timing the stopping of Phant, data was streaming in and corrupted something.

To date my successful workaround has been to edit streams.db down to only (what I'm calling) one entry per title (`{"title":"myTitle","description":"myDescription","tags":[],"fields":["myField1","myField2"],"hidden":false,"location":{},"id":"myId","date":1481547878295,"last_push":1486439379499,"flagged":false,"_id":"someOtherId"}`). I then start Phant again and all is well.

Is there a better way to stop Phant?

**Comment by tbitson** [comment]
How are you launching phant ? Directly via npm? 'kill' seems to work without errors.

I personally use the forever script (https://github.com/foreverjs/forever), to start and stop phant with the added benefit that forever will do its best to keep phant running. Simply type 'forever start phant' or 'forever stop phant'. 

- Tim

**Comment by structure7** [comment]
I have installed on a Raspberry Pi that does nothing else, so I just `phant` in terminal and leave it be (headless remote with xrdp), however maybe that's an issue. Let me try forever.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
