### ISSUE TITLE
Uninstall phant?

### ISSUE THREAD

**Issue by lautiamkok** [sparkfun/phant#218]
How can I uninstall phant?

```
$ sudo npm uninstall phant
npm WARN enoent ENOENT: no such file or directory, open '/home/username/package.json'
npm WARN username No description
npm WARN username No repository field.
npm WARN username No README data
npm WARN username No license field.
```

**Comment by matrixfox** [comment]
It's not pretty, but just delete `phant` inside of `node_modules` folder. Or just delete `node_modules` all together.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
