### ISSUE TITLE
Data.sparkfun is down.

### ISSUE THREAD

**Issue by tvirta** [sparkfun/phant#219]
I can't get to streams.

**Comment by tvirta** [comment]
502 Bad Gateway

**Comment by rdrink** [comment]
Been seeing this all day (since about 10:30AM CST). No one at Sparkfun seems to have noticed (or at least done anything about it).
Might be time to give up on phant. No significant updates in over a year.

**Comment by geertvw2** [comment]
Yes indeed. We lost in the meantime 24 hrs of our Internet of Bees project. Since this happened just after we made an important intervention we wanted to monitor, this makes us very unhappy. Please Sparkfun folks, get this solved quickly!!

**Comment by ebeeche** [comment]
Just like everyone here I did suffer all the mentioned problems, so at the end my solution was to rent a virtual server for $5 a month and host my very own phant server, headaches gone!.

Phant is a great IoT platform I really like it, it's kind of sad to see Sparkfun is not interested to keep it alive.

I am (slowly) learning the internal parts and bits of Phant just to be prepared to keep my server alive (and also to help other people if I can) in case Sparkfun finally pulls the plug.

Greetings from sunny Costa Rica.
