### ISSUE TITLE
DATA.SPARKFUN is down since long time 

### ISSUE THREAD

**Issue by aroraElectronics** [sparkfun/phant#221]
DATA.SPARKFUN is down since long time 
what is issue how much time more it will be down
when it will come back
What is other alternative with similar interface i using following way to publish data
AT+CIPSTART="TCP","data.sparkfun.com",80<CR><LF>
AT+CIPSEND=126<CR><LF>
GET /input/QG8rp2jL8yidlGR18Yr0?private_key=XXXXXXXXXXXXXXXXXXXX&lvl1slot1=FULL&lvl1slot2=FULL&lvl2slot1=FULL&lvl2slot2=FULL<CR><LF>

any other free streams give above interface

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
