### ISSUE TITLE
Data didn't show in the stream

### ISSUE THREAD

**Issue by katiehn14** [sparkfun/phant#225]
I have an issue that in the tags showed the last minute of data being pushed, however, the stream didn't show any data. Maybe because of the bad gateway.

**Comment by khanafin** [comment]
Same issue here... shows '1 success' in response to curl GET command but data does not show.  CSV request shows no data. When looking using 'tags' it shows recent push.   Any clues?  

curl command and response is: 

curl -X GET 'http://data.sparkfun.com/input/Davrxw2vbNSljpMA1J2X?private_key=Pnd05GYdEKsxYgqaBm0d&ard_ts=3221771&orp1=246.30&orp2=0.20&orp3=262.70&t00=23.50&t01=24.14&t02=24.89&t03=24.82&t04=24.38&t05=24.07&t06=23.83&t07=23.32&t08=23.44&r09=23.50&t10=23.20&t11=24.82'
1 success

Thanks for any help!!

**Comment by khanafin** [comment]
Workaround?  Made a small database that was able to save data to.  Renamed and replaced data fields to replicate the earlier stream... worked!

**Comment by rryansilva** [comment]
I am having the same issue with the stream:

https://data.sparkfun.com/streams/6JVyY4a2WDF88ZA6r01m

It returns '1 success' but nothing is appearing in the stream.

**Comment by rryansilva** [comment]
Interestingly I set up another stream with the same parameters and it is behaving the same way:

https://data.sparkfun.com/streams/GEGJARbxRjfW9MRVVbw8 AKA https://data.sparkfun.com/bekasi

**Comment by PaladinEng** [comment]
I am also having this issue. I had a working stream. I even posted to it this morning, but now I'm unable to post any data to the stream. Also, I'm getting a lot of 502 Bad Gateway returns.

I'm using postman to test my POST messages, and have simply re-sent previously successful messages to test. So I know that I do not have a formatting/construction issue on my end.

**Comment by jgpender** [comment]
I would also like to know why Phant periodically goes offline. I am posting data from an ESP8266 Thing Dev and it was working great earlier today and then went dead. The Serial window (Arduino IDE) shows the ESP8266 connecting with the local wifi and claims a successful post to Phant but no data is actually visible on Phant.

I would also like to ask if it's possible to host a Phant server on an Arduino Yun. I have several Yuns on this same wifi network that could be logging the data from the ESP8266 (which is running on battery power and deep sleeps between each logging event, so boots fresh for each data point).

**Comment by NJJLClub** [comment]
I'm also having issues. I'm getting the '1 success' returned to me but I don't see the data showing up in the stream. I also very often see the 502 Bad Gateway message. Then I refresh my browser and I see my stream but it doesn't contain any data that I sent it.   This is my stream: https://data.sparkfun.com/streams/7vGGnEw1DmuZ23DrJ99E - I posted a number of Temp and Humidity numbers to it but don't see them.

I was able to post Temp and Humidity to this stream with some success. https://data.sparkfun.com/streams/6JZbNolApzF4om2l9yYK but not the one I created.

**Comment by protchenkov** [comment]
Exactly the same issue here. Getting 1 success via postman and Arduino, but nothing appears in the stream: RvrWL47WpjHqj6K2mJo3
I'm also getting 502 response once in a while

**Comment by rryansilva** [comment]
I contacted Sparkfun customer service on this issue, and they indicated that they are aware that Phant is not running as successfully as it once did, and they have a new tech who is working on updating the platform, which has of course been in beta. 

I have some streams that are continuing to run successfully, but I am switching to Adafruit.io for new streams for the time being. I look forward to Sparkfun's updated offering and would be willing to pay for a premium tier to help support the project.

**Comment by rcnerd** [comment]
Same problem. Previous comment gives some explanation... and in return satisfaction that I am not going crazy. There is no way to up vote this issue so I am just leaving a comment.

**Comment by THALLIVA** [comment]
import RPi.GPIO as GPIO 
import time              
import httplib, urllib   
import socket           


server = "data.sparkfun.com" 
publicKey = "vV582NgNM2uzAMjr03Gy" 
privateKey = "aR1rD929ADhamg1MEPJz"  
fields = ["time"]

print("Here we go! Press CTRL+C to exit")

data = {}
data[fields[0]] = time.strftime("%A %B %d, %Y %H:%M:%S %Z")
params = urllib.urlencode(data)
	
headers = {} 
headers["Content-Type"] = "application/x-www-form-urlencoded"
headers["Connection"] = "close"
headers["Content-Length"] = len(params) 
headers["Phant-Private-Key"] = privateKey
	
c = httplib.HTTPConnection(server)
c.request("POST", "/input/" + publicKey + ".txt", params, headers)
r = c.getresponse()


print (r.status, r.reason)
time.sleep(1)
	
	
	
	

I wrote the following code..I get 200,OK but didnt see data on the stream..

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
