### ISSUE TITLE
Issue while loading the output stream

### ISSUE THREAD

**Issue by tanmayee30** [sparkfun/phant#228]
Hello,
I have 8 data fields to be uploaded on phant. After firing input query from browser i'm getting result successful. but when i open the dashboard to see the data it is showing me blank page. 

Any idea why is it happening?Is there any limit on how many data fields we can generate with one stream?
Also can I remove the by default date and time which is present on output page?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
