### ISSUE TITLE
Setup issue with Mac

### ISSUE THREAD

**Issue by Sophi** [sparkfun/phant#230]
I've just installed phant -g, Mac OSX.
I'm having trouble getting phant to start. What am I missing? Thanks!

<img width="420" alt="screen shot 2017-07-06 at 11 59 25 am" src="https://user-images.githubusercontent.com/1236607/27920448-9a9cf6c6-6242-11e7-8e31-c0632b100839.png">

**Comment by jmcgnh** [comment]
On linux, the install creates a link at /usr/local/bin/phant

Check to see if that's present on your system. It could be there but you might not have /usr/local/bin in your normal PATH variable, so just invoking "phant" won't find it.

You would need to provide more details about how you installed phant and show the full path to the node_modules folder where phant was installed for anyone to give more advice.

**Comment by Sophi** [comment]
Thanks. That path /usr/local/bin/phant is not present
Phant is installed /Users/sophikravitz/.node_modules_global/lib/node_modules/phant/.bin/serve

I installed phant in my node folder like this:
<img width="970" alt="screen shot 2017-07-06 at 12 20 44 pm" src="https://user-images.githubusercontent.com/1236607/27921484-edaf1972-6245-11e7-8bab-bf5a25e5cf43.png">

**Comment by jmcgnh** [comment]
The .bin/serve file is the target of the link I see installed at /usr/local/bin/phant

You could try running either

    /Users/sophikravitz/.node_modules_global/bin/phant

or

    /Users/sophikravitz/.node_modules_global/lib/node_modules/phant/.bin/serve

to see if that gets the server started.

If it works, you could choose to make a link named "phant" in a directory that _is_ in your PATH.

**Comment by Sophi** [comment]
Thanks! That worked.
