### ISSUE TITLE
Is phant server down?

### ISSUE THREAD

**Issue by xGhino** [sparkfun/phant#231]
I can't seem to post data into my stream even to it always sends back "1 success" when i go to the url. Is there anyone resolved this problem? thank you in advance for your reply.

**Comment by floresta** [comment]
This is essentially the same (unanswered) problem that was previously posted in  #225, and #228.  

I have been able to post in streams that I created earlier, but not in any that I have created in the past month or so.  Here is how I see the situation:

- A new feed can be set up with no new problems.  (The confirming e-mail is never received, but that is not new).
- A proper GET request results in a "200 OK" response.
- A proper HTTP request results in a "1 success" response.
- After either or both of the above, a check of the feed results in a page with no column headings and no data.
- A request for a CSV results in a "no data has been pushed to this stream" response

.

**Comment by floresta** [comment]
It looks like some progress has been made as there is now some evidence that the problem has at least been recognized.

The link that formerly invited one to create a new stream now says: "Sorry...phant is currently not creating new data streams".

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
