### ISSUE TITLE
Error on create stream and can not create any stream

### ISSUE THREAD

**Issue by gaew** [sparkfun/phant#232]
phant http server running on port 8080
phant telnet server running on port 8081
HTTP output: { Error: ENOENT: no such file or directory, open 'phant_streams/35b1/36f064a411e794ff6b9f26be3c01/stream.csv'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'phant_streams/35b1/36f064a411e794ff6b9f26be3c01/stream.csv' }

**Comment by jmcgnh** [comment]
The name of the stream.csv files are derived from entries in the streams.db file. What do you see in your phant_streams directory and its subdirectories? Is it possible there's a permissions problem?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
