### ISSUE TITLE
Not able to Edit my pubblic stream

### ISSUE THREAD

**Issue by Albertorat** [sparkfun/phant#234]
It is few days that I try to modify (editing) my pubblic stream without success. I always get the following  message : "Stream creation Is currently disabled".

I need to correct an existing stream! I do not need to create a new one, is this a bug ?

Could you please let me know when stream editing will be back?

Thank you

Alberto

**Comment by floresta** [comment]
You probably should take a look at the information in the sections with a red background on the main 'data.sparkfun.com' page and draw your own conclusions.

Don

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
