### ISSUE TITLE
Is there any way to access an index of data row?

### ISSUE THREAD

**Issue by elimorris** [sparkfun/phant#235]
I'd love to be able to query a date an have Phant return an index (sample number since the beginning) for that date. I think about just adding an index field to my data, but it's problematic. What if the power cycles on the datalogger and the index starts over again. I can protect again that, but it would be much more straightforward if there was an index associated with each data point that I could access.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
