### ISSUE TITLE
my data stream is gone though was working last week :(

### ISSUE THREAD

**Issue by NiallHurley** [sparkfun/phant#241]
Hi, 
datastream appears to be gone - was working fine last week - will it be back or do i need to work out another solution?

**Comment by NiallHurley** [comment]
(on data.sparkfun)

**Comment by edmaher** [comment]
https://data.sparkfun.com/

**Comment by NiallHurley** [comment]
thanks - I saw that - i've been hitting 'refresh' on my pages every day - looks like i'll need to figure out how to do some HTTP requests on my electric imp...
