### ISSUE TITLE
"Feed Disrupted" notifier

### ISSUE THREAD

**Issue by nseidle** [sparkfun/phant#37]
Wunderground has a really neat system that notifies the owner of the weather station when it has not reported data after 2 hours, then 24 hrs. It would be a 'nice to have' : an email when your feed has not been pushed new data after 2 hours have elapsed. The wunderground feature has been crucial when developing my station and is a great notification to get.

The user should probably enable or opt-in this feature. 

Here's the email I envision:

Title: "Data Channel Alert: [name of channel] Disruption Detected"

Hi owner of [name of feed],

We noticed your feed traffic has been disrupted. Click here to see the latest log.

We want to let you know so that you can check your hardware if necessary. Click here to change your notification settings or unsubscribe.

-SparkFun

Here's the wunderground error email for comparison:

Title: Wunderground Alert: PWS ID #KCOBOULD115 Reporting Error Detected

ATTENTION: Weather Station Owner

The Weather Underground PWS network has detected that your personal weather station (ID #KCOBOULD115) has not reported to www.wunderground.com for more than 2 hours.

Please check that your station is operational by visiting your station's settings here: http://www.wunderground.com/personal-weather-station/mypws

For more details and information about troubleshooting visit our PWS wiki page: http://wiki.wunderground.com/index.php/PWS_-_Personal_Weather_Stations

We want to ensure that you are informed on the status of your weather station so you can continue to receive accurate data from Weather Underground.

Thank you,
- The Weather Underground Staff

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
