### ISSUE TITLE
Putting private key in HTTP post makes protocol vulnerable to man-in-the-middle attacks

### ISSUE THREAD

**Issue by jacgoudsmit** [sparkfun/phant#49]
I haven't perused the code (yet) but it seems to me that if an IoT device has to make a connection to Phant.io via HTTP (i.e. unencrypted) and has to put the private key into the POST command, this can be easily intercepted by a third party between the IoT device and the Phant.io server, and can be abused to post false updates, or do other Bad Stuff(TM).

Private keys (by nature) should remain private and shouldn't be shared over the network. That's what public keys are for :-)

**Comment by abitmore** [comment]
>There are absolutely methods which enable us to push data semi-securely over a non-SSL connection, such as using a TOTP code, or by signing requests with the private key, but they all have their own issues. Ultimately, it's adding unnecessary complexity, and it's attempting to come up with a solution for an issue which is already solved.

@Nick-W what's the issue of "signing requests with the private key"? 
It's not needed to sign the whole request, but only to sign a one-time and always increasing magic number, then include the public key, the signature and the number in the request. This will need less computation on both client and server side than the HTTPS solution. Anyway this will require users to play with cryptography in application, thus not perfect especially when a TLS/SSL termination proxy device/solution is cheap/easy to deploy.
