### ISSUE TITLE
Output Data Decimation

### ISSUE THREAD

**Issue by surfingsteve** [sparkfun/phant#80]
Sensors might log data every minute, but you might want to graph it averaged over 1 hour for the past few weeks.

Can there be a new API field to request every 10th sample, or avg etc.  This would allow for substantially less data transfer when loading a long term graph.

_Enhancement_

**Comment by jjcf89** [comment]
Sample doesn't appear to be documented, is this still a thing?
http://phant.io/docs/output/http/
