### ISSUE TITLE
Integrate data graphing / data visualization to the data channel

### ISSUE THREAD

**Issue by bri-huang** [sparkfun/phant#81]
The folks at manylabs have a pretty slick interface with a data channel implementation they built:

https://www.manylabs.org/hub/data/

I think their stuff is open-source, but I'm not finding it easy to find their repo.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
