### ISSUE TITLE
Running on Heroku

### ISSUE THREAD

**Issue by emcniece** [sparkfun/phant#86]
Just trying to set this up on Heroku and wondering if it's even possible. Git push returns a message:

```
! Push rejected, no Cedar-supported app detected
```

Makes sense, by installing phant at a local directory instead of -g there is no init files in the main folder. So I followed the [Heroku node.js](https://devcenter.heroku.com/articles/getting-started-with-nodejs) tutorial and at the very end I swapped the Procfile content from this:

```
web: node web.js
```

... to this:

```
web: phant
```

However, now when I browse to the heroku app URL it fails with ERR_EMPTY_RESPONSE, and browsing to the :8080 and :8081 ports give a ERR_CONNECTION_REFUSED. 

Any tips for making this heroku-friendly?

**Comment by jallwine** [comment]
Did you ever get this working so your streams remain intact after a restart?
